# Generated by Django 6.1.1 on 2026-10-01 18:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoPlanilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('MOODLE', 'Moodle'), ('TOTVS', 'TOTVS'), ('HISTORICO', 'Planilha histórica (migração)')], max_length=20)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('semestre_referencia', models.CharField(help_text='Ex: 2026.1', max_length=10)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-importado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(choices=[('PORTUGUES', 'Português'), ('MATEMATICA', 'Matemática')], max_length=20)),
                ('semestre_prova', models.CharField(help_text='Ex: 2026.1', max_length=10)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('origem_dados', models.CharField(choices=[('MOODLE', 'Moodle'), ('MANUAL', 'Manual'), ('HISTORICO_ANTIGO', 'Histórico antigo (sem % calculado)')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_provas', to='alunos.aluno')),
                ('matricula', models.ForeignKey(blank=True, help_text='Snapshot acadêmico (curso/período/turno) daquele semestre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provas', to='matricula.matriculasemestre')),
                ('importacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proficiencia.importacaoplanilha')),
            ],
            options={
                'ordering': ['aluno', 'semestre_prova'],
                'constraints': [models.UniqueConstraint(fields=('aluno', 'disciplina', 'semestre_prova'), name='unique_prova_por_semestre')],
            },
        ),
    ]
