# Generated by Django 6.1.1 on 2026-10-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_ra'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nota_matematica',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nota_portugues',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
