# Generated by Django 6.1.1 on 2026-10-01 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaSemestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre_referencia', models.CharField(help_text='Ex: 2026.1', max_length=10)),
                ('periodo_no_semestre', models.PositiveSmallIntegerField(help_text='Período do curso que o aluno cursava nesse semestre')),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=10)),
                ('percentual_curso', models.DecimalField(blank=True, decimal_places=2, help_text='Calculado: periodo_no_semestre / curso.duracao_periodos', max_digits=5, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='alunos.aluno')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.curso')),
            ],
            options={
                'ordering': ['aluno', 'semestre_referencia'],
            },
        ),
    ]
