# Generated by Django 6.1.1 on 2026-10-01 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matricula', '0001_initial'),
        ('proficiencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculasemestre',
            name='importacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proficiencia.importacaoplanilha'),
        ),
        migrations.AddConstraint(
            model_name='matriculasemestre',
            constraint=models.UniqueConstraint(fields=('aluno', 'semestre_referencia'), name='unique_matricula_por_semestre'),
        ),
    ]
