# Generated by Django 6.1.1 on 2026-10-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('duracao_periodos', models.PositiveSmallIntegerField(help_text='Quantidade total de períodos/semestres do curso')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
